language: java
jdk:
- openjdk8
- openjdk11
- openjdk12
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  - "$HOME/.cache"
  - "$HOME/.gradle"
script: "./gradlew build"
jobs:
  include:
  - stage: Deploy to bintray
    jdk: openjdk8
    script: skip
    if: tag IS present
    deploy:
      provider: script
      script: "./gradlew publishPlugins"
      on:
        tag: true
        all_branches: true
env:
  global:
    secure: LERlTO8/SESCg+kMdjc10+yXWfRdAWNawQlhq6GZk143EK0JHifPcbia5JOPjnEECUtELYlsPAI0ZWMhKoDgq9mVBiqX8ghubTO0k1TPMm2zsjAeXYoIyhZpyy6y8vdvrV5arUm2GUXf5xL+GdoUBojFy10IbrAlEm/xJTh8rChowxU1yidTUVjX5P+CGJQuxNUY4vtHxZrYY5hkZls5mElMSv5pM/z5k50WfuBbuewYtn+7i3UETQngJ9nmDS9j/9OXcJN3x6v40SdEwss5vHxle08/CpX31RMDpC5jKlNiV5HQFZJRQkiAkJkup0ia0/n5AoC3L4pFWwNjb3+AaxYkUGCGFJsmGMNb3nIHBfsC3ORe52iyMWtVV3E7JZxf7m0U33yHngM92kCUuMf4x9O7Xg7tZc6phmvcHieBpKxNkhWP2yYFaecgdzYk6s3H1dOtB5mGUIypH13msn08fkQnL+NRNJjl919MJuEECNC3xxK20S4kpj6WkJOcNwljhK/lmt/Hz4gdqc6XucNZOQoFEt8XNXacXQYE/DgG5RV4HalLx6OXEfUNWjUDcPH8NjxabIq9HseJ+Opacraukwey5QygRPZ8WRWTXO06qhV8xZ051QClp7rN5px7zMK1nJ23jsdDTzJnHc4YF8nYxtn1+y/z4pEihP++lUO+Wuw=
