language: java
jdk:
- openjdk8
- openjdk11
- openjdk12
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  - "$HOME/.cache"
  - "$HOME/.gradle"
before_deploy:
- export gradle.publish.key=$GRADLE_PUBLISH_KEY
- export gradle.publish.secret=§GRADLE_PUBLISH_SECRET
script: "./gradlew build"
jobs:
  include:
  - stage: Deploy to bintray
    jdk: openjdk8
    script: skip
    if: tag IS present
    deploy:
      provider: script
      script: "./gradlew publishPlugins"
      on:
        tag: true
        all_branches: true
env:
  global:
  - secure: Z3hAd2IpaM80btiV105hzfNC/4jzUmnnyAHgGPQ1KWvxqCRt9Qgy/lIH4CBYia8K/aQ3kbbrNAsD8Axgtk6Ap58LgvpSKvYB2BMpaOgSbDTDR7lberjkRk2wpMmcSH/ThgwkRM0Io1qYA6bS+Y0YgK0Q2eEbHP8KrhS8FU+SiQ3H9wixbsfm6SC0U3jqMkTGoR0tuR3DgYrQHrnPZM4hepSSpFxCM/QLLKfgoIwREZLMn3ym2LVgCdncuCkzYPu1UKupU7nUPg8HwwOGeR0EEOt3YoK+1NDx+HVlA3P0YDo6wG+myEoivR7hk2c+47XSa9ZHIyZIWZo9A2jVFPM4fwzWqDIJGNxnXcFQmjX+aw3xTP6DBhzWEMzSevRUCc1qivPbz9Lr/D9QmAtLywZAbrlvtETmLw413DSmwPQnBlC+kFwScfTYk1YGI/7oJe2lXLiE9InncJbC0Som6UDesmhSxIe4K60SGFNoVs3JmvNIyKEP0fcH0vNB7GpUjGwJ4jPpkUmoEXtzuG08eb8RvDFl+BCaz0Xv/i2U/5tNCzqR8PGC46UVc4uFl4QHjhG/1/hDTCX8OjysKEXuaThfLjbJTIllRger4AXULTnQSkpY1iz24uaT0hPPSv6mr8qgzlvi7TelkWWtOOVqW8maai906Wlrzpjpm4pqASy0DE0=
  - secure: sd35z6nCkJTY9kVt2A5x2pAH4Kpufx6IPnazXYn5myoUSuOHrApMXK53tiWAt3s61Gx+PZiObssqOIsu0kCXwiZ+I/WKqEB5O+O/KdBO3WZcHS18BlidPLV4ELW+4QOeH89V2fG9LH7aJeJSbHNe/W6lqe6UPIH8w454M95fxtg2/WdS+GW/QywpQ6UUanRRvauqnKL9CEQP5+YhgmzVNjyPvEr7RffIqklYvDrKvtpxye9p5EFdueTLl+Q8erdiCEjZVL+tiCVz74R9RtxP6qkSxab+hPcrgSpjEYS5jnNcpX7OW94J+KhO6hIcuVlg3WenDSJEKDBy585TtxEtUkGLFoFqOHijBV6t1dd2ZuTLMyOh6wbZohYWPUie+yEnF+fCZxshbEkUUq2wUUkUTA2Vhb/SLBLP6S2QmphuxRKMrXAbsDZ5qy3ASeHU0l86DBEJs7NjdWd9cnZM0/XuZu8o+YICpzB63X3F4Jk1tJEJo2pC5U4V72auTMR4/Mj48JVD3XW//p2NDBRh18poYSPTtN2n1sYXVnDSAro9EBdyPSY4wL3LIHlgYJX0pUmKt5maAmMakYDREOmx6E5L2qEYMPIqLdYMF61BI+4+NNiiuHz+imVDqlcw7ysCOdTO5G1owTePU7JvHEeP7GHTpkNwXzaH7Q+O5C9/Ci5g4sU=
  - secure: R6lVw99L5+ZEhIimKeXWvb+YjWFn1Aih2Br4Zq5NvNc0eIuHkI/TQrpW1nBu4++upHzt3wzq0rjLN46msT9U8NSV7yiW5c28DP8hylJh4r9V7BeaeiWFlcyzmpDQSPPvIoBB8uaUlh7F2lb1zK+QM1/B2bYHmPgvUV3xqVhHfU8LyqTW7QOtjKIODFegaylUQmFpj056uxF1DVTFboJlnYexG4E/FOhWGzCnLvN2mQNyDxTZ/nv1ip+8pDpmt9vl3M4DTe8dzJD4MDwcyOT7rA4JvspN2NgYR6yqiRIpEdr+4rl9+pKdoXaMvpm+VTFklzdOBGan2mvML1UaGaJYdlCvHIDY4JBG1Ivb3NIbrKHdM+w1OR6K4K23z6EI998IkcDTREQTgB/1ka5I2HJMFtUU7uS3bVJSSV0ROu/lg5/p88ohDWOYMoNWg0xQxwy+gyrY9sJnu5NQ/qnXyr7me4Gq2julDNrKzX6ve8Yy3EI7MfrfbQVf4wk7ri02aASehiH+OrkXQLcMrFG+kMJ0aIte2GCx77l6Whytj+cBK91Z2PMx5R5ec7szItryV0Pvs7sRAjyIsRotCOWQszzSjJYSuiCMpliPM0T1SJIBUI4R54bAZ71m5fhyWRc9WwuQFRPm/41nbsNZjdqNPL27sZ32z5wUKj2idhFgEG2TmMA=
