language: java
jdk:
- openjdk8
- openjdk11
- openjdk12
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  - "$HOME/.cache"
  - "$HOME/.gradle"
script: "./gradlew build"
jobs:
  include:
  - stage: Deploy to bintray
    jdk: openjdk8
    script: skip
    if: tag IS present
    deploy:
      provider: script
      script: "./gradlew publishPlugins"
      on:
        tag: true
        all_branches: true
env:
  global:
  - secure: t6cTZWxFDk8gykRiipUJTzBM0Ao1jbUZo8pnUwBAAwuoF/cxFA7WPHzn84Nl6s8fPdJYqUDV6oDyzJgLZy2w7+XEdnMdpYUOaksGotFRkBtcHnY6Go2GLYeTLXBU+nx4eieHg8Yw5Oage1BVTNdHbdrvwTFEKrWOBUz5YV8O8qqPlpgPZKfFCxni4J1RkjXa+xKxofUkSDb0b2hnUycrqEGLL6rEjbfzhXJZ8HZ81eIwDE2iurQigrcJgz9NnFdg2m5YZ6AYhvIEOzYsJsjX1IAG2fP6LcMUppWHgq9xxqq/h6nXoxk4e/0vDWAZZVlX/2Sps3sfGyLQhlv26+bb1cKFn8OxBRKYlLJpSSZx8FWkVPY2wpU+pqwbYjO5//tPK9MCZsKaOY8+kHq3rTbCcMx5xWXxfLiAzFTEAX83cqPoCMd31Gwlcw4jT/RQafQq6YqIRxBUpQbwoipFnIDUy52I3SUwk+X6dFI1lcViaEztdTnlzYZhqRqFoop69cbUVyxEvND2YxNh3QtoTbiaw9BsdSXxPp5SvHC2Wmm1utnC4yK5OBHAt9+TTlO6OLlYFmHiJ+NTAA21PVeH+T1MlpI9rWU/+Utm06Ne2l6vrKSAmK3qBpTctCxIS6TfOGw6Ob2oO4ZifZ5mmgZ2b6MbiLvLyGoWEnb8HvSvFsAMcBk=
  - secure: Akm2PfAHIF2zogSqQkiUHhyeW9c9oyDQML5fohfmgbZ3aLeAg1T7rNsJnmDOSGMEPJus8G5dtnXbxdr9X1qKCpahp19nZ69ung0QQXt2yhLWoly+QyMkGcC1d5Nnhg981WtTdwU/mmiu3ijUs3ajlS2YiK/roQehV2VcJISOE8r56x9uyLl3rFLTD2/q8kwyedCKb9kltcw7G8tOmAi0E6od+VGk5Oy6Gs16BuWPYhk/FJBqDFMfbENAvJo16TYYe4xpiMZQJJlDxP1dsVuzw1lk/fwEyQxc/Rgj2HilEpaQmBrf35nQ9bzqGVEsJ0nO0hv4EIgAnRDGdtKWVNBhSnobCq6QbsM/xadXJENUB2Cv6yMv6qiNaLRiNLS8+ddKxtpibohNJCn9CZRtxPvH6wtl6k9oWlXcRV+pY4XVpeiqNG5lJxNemp4S5POsVI2B67HVsawSRNmki/+cnSk+vvHEBFrorQmyerwY1LpKiWACj/3jf7TjGeL0jJqPXNLVkQn5fVa58183MjsIv4HRu4dh6cK8SLbOJqMd5+GJzo9j1rEmSGjU8eqJtbUdkPJ1iwWDaNVak0QOk+/UUbyi4eVoSKz935N8s/acdkzVFqnmAbBWDFmOFDVFK9aBDs7DUiswlmlrzq1yeVi6yBfGw1cGR/rqqjfpjkhlTYP3mCM=
  - secure: Y6dZ2plnzLm1aa4EqWi5RdTkj3gukaCoarhcVhy/2E7uxoY9RQ4AKZmqg0jM15wLVibqS3q2qQS6bx0i7XP7NA+hR/jpYsKANNkpyJ0HiwxWE5B+MFG2snzJQ7hoE6RlJHZLOmuFr7qR/c8/0BYmCjDVSVKnvnw1ozA2o7M0Rit/rZQaYICS/oyaHf0IyV+oqbibJ65MB83zy+ZuvVsM4e/o2I3MaeDxapLgA2DWxhFfaKL0wDOhlSYJc5cw7fWXKlMqfOe+FXGh1xaQkLbw+Iwinsi3iuf0VziqJnRG0UKPczA0PlRTRoTNb23a2dqgz5SPcFG4l6xM7pAq5SxUFaMjP6brdek/mj3Hz9ilg4JvJh+vGCbrzHg2NJyb692xIA5CtznCsqr9a85cdJ0j3J06q5vA8Hbofi3gOwwW4LcwabD1o0Mt5HfxyVp+R0cu85U22EOT72K51mMoVzZPRax/7MWvvJcNPxgpmP1wpbdj6ZPlyyIsSyy7hVFgBEBdqjT6abJyT2n3+V9tAbmfuGwEE1qMEPBAYdaMVYxtOeGpF2KKsyBkKZzR5WcAJcl5q+y7zlPF+BbZfzYIUA3t9PKG4q9uDGhncDsStn5R+9rHTlfDwYnCMzQEgnKAil3mXZUwrL9K3cRvLSCY6E3cNjqbbllQv9LH1XiZSefpuYE=
