language: java
jdk:
- openjdk8
- openjdk11
- openjdk12
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  - "$HOME/.cache"
  - "$HOME/.gradle"
script: "./gradlew build"
jobs:
  include:
  - stage: Deploy to bintray
    jdk: openjdk8
    script: skip
    if: tag IS present
    deploy:
      provider: script
      script: "./gradlew publishPlugins"
      on:
        tag: true
        all_branches: true
env:
  global:
  - secure: LERlTO8/SESCg+kMdjc10+yXWfRdAWNawQlhq6GZk143EK0JHifPcbia5JOPjnEECUtELYlsPAI0ZWMhKoDgq9mVBiqX8ghubTO0k1TPMm2zsjAeXYoIyhZpyy6y8vdvrV5arUm2GUXf5xL+GdoUBojFy10IbrAlEm/xJTh8rChowxU1yidTUVjX5P+CGJQuxNUY4vtHxZrYY5hkZls5mElMSv5pM/z5k50WfuBbuewYtn+7i3UETQngJ9nmDS9j/9OXcJN3x6v40SdEwss5vHxle08/CpX31RMDpC5jKlNiV5HQFZJRQkiAkJkup0ia0/n5AoC3L4pFWwNjb3+AaxYkUGCGFJsmGMNb3nIHBfsC3ORe52iyMWtVV3E7JZxf7m0U33yHngM92kCUuMf4x9O7Xg7tZc6phmvcHieBpKxNkhWP2yYFaecgdzYk6s3H1dOtB5mGUIypH13msn08fkQnL+NRNJjl919MJuEECNC3xxK20S4kpj6WkJOcNwljhK/lmt/Hz4gdqc6XucNZOQoFEt8XNXacXQYE/DgG5RV4HalLx6OXEfUNWjUDcPH8NjxabIq9HseJ+Opacraukwey5QygRPZ8WRWTXO06qhV8xZ051QClp7rN5px7zMK1nJ23jsdDTzJnHc4YF8nYxtn1+y/z4pEihP++lUO+Wuw=
  - secure: uyVPJdsYMbcWzJ1MUoqonRQVKHIYWIfYrIbXtVi7/b3A3RQyoCk43V/WC82lRHQ6imq4I8/AJdhaj4Cif1kQDrTi+9+hjgh6Wwy4PDIEHYWkzDzw77+oTWpg+uzAh4EsU32ilRrKXS9+T7U8epTgKDlYQN/9xfxNRJHsTF7POSqWn7QDGG0R/2sQB+U480xEo5IFMlupPMQpOOHPYPlKJyhEGtXVctw3PsDXJlkg0i7WHgY/v3W6o+7bFknMsLred0QiI9yCtk3z1l/cyvPjHPGTxvgmGar+ny0LLItUvJR7THHmC0he7TzfZantsODwHqq3L/+MWCvJpOYwRVpB/f8QxeP4crgMzNh3AJtzti6QsJaS7KOXl7Gr18OS7FFDybotI3+GnYPzvfUvNmFLGb8jAyH8XblxNmmGrY7nbvP4N2UelP5g2QOdKI0TybDLIslE2yeb1HARLqaP5gmFUpkxARcw92pd+szjRZpTVt8mnGoeHSBkzuu9JLSxOtblii5Yh6zc8H6A9/GQoxxLBYRvlyiplNFSYMaOXbxkdIj1jADTS30TmVMbMn1KnygbVNT6w47Y0cbGumv6qoQ1dfn/p1/bGXoDhTf/tDiddAEN15jp2TruYtw7haP54mG7lgr4sXjvRkiBmjiooa4CQT4HyXJ1z92+nVLsxB7rFNU=
  - secure: FSpqZUSLKZ1GgA1ToMG46mcnlVe1vJ/EyXA28WqLHDUluzDctZ56nRJmzrzqFPRT5CmdLEr42MBr4ijlinBF3W88nLugP8kV1ZtjQmWn96AfxSrNrSrI/zZ4mDzuVJ2L1CIp6HBWTiF8VLLGBNv7KBae6ZMq+hg2WdiJ2QLff8GjvVEM5y6LqE03C4tT/v2jHObbP2COKP4KXRJqx6kV8UW5g/4SFTgmjCaLaKO0zF/YzDQyPVK+RaiRqCPUGdIvw7DrHYO/sBi9jUP+0bpakrGOBvWnUGOPEkeWAETsWaNuY9jGxOPmOUQFtXZXFKwRG9syO8l1C1OWQM6yDAO/mBMNAiLmWMdAQ2y6NfVS5B/QseotyYtrLu/GIRcSMmL8SE/2B70YkMAlaUazFqy94lyYgCZUbvWeMxuusc5liuU5Ee5HzcsqqGEIQ/Znyw1ZFh166ymMuE2ccsyUSyjpkocaQu6lCFpcG9MapfU+KulcjI+nRLwJfU3myX7qIaaXf62HeLN8ZpgHs805AziN8SJjk4Y+LRlCd/+yFHJz/kKDKrN6iPQVVeYbquthHLqSWqzwzV0sM8jI5i6EOqc9R7vCwRwiBeijtoG19UDCDEz85j95sWl4OxPSUTxkc4UBzlrpG+JJbF/rtMGWwARiw7n0j0HzOljnDYKoJ0PaKLg=
