language: java
jdk:
- openjdk8
- openjdk11
- openjdk12
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  - "$HOME/.cache"
  - "$HOME/.gradle"
script: "./gradlew build"
jobs:
  include:
  - stage: Deploy to bintray
    jdk: openjdk8
    script: skip
    if: tag IS present
    deploy:
      provider: script
      script: "./gradlew publishPlugins"
      on:
        tag: true
        all_branches: true
env:
  global:
  - secure: rnqzKjsKbXTyinIEQofuQZVcLoEuUg6uvynN1ewX/4dTGOghJh9ZpuIvBmXErehI0EiFNmSGHEVXR819YiGthm5oU46kPSn85jBH/YjwrPI2a6VL2AqFg8lbC9couEVf0U6U8OHZKMHr6X+EL4oOR/oqF738ppLeOvSnpstukOFV7z1mfTrhPQDvePj+4lDiXzfLfATyZUSH0fw3jMc6MYNjBipVna0IPgw4oqFnlqW2mz0UvOYZBSIitl+iumZviFUGZyZNhsZaqQ+nMQTI0U+f5FYkQfYa1/Rx5wg/VY7Ia61M1CcKRuy1S/XRNz+EyC+Yd5jLefiGoNpSg2D7a/GmFsOQdYGD61i7/N37hUYCkKDv5ArudSI1otVvMV8pNx4gdrvD82dCKcJipPQ9V4kpZIcjfm51gXuplV7W+2WtvxCYpyjhzWCzFAM+F76paMvGcm6QL364OUldeMHU6k5O+X4fAwEkxNzVT77GQoXqdVhvSQGsHACSpU+ZurMZzYNweVpvI5yNcjArZF/NZ5++R88JmpFAofWp8yLy64jE0rNyXnyNd9E5mvlR/2rC4kJKYG/tZGRTxXFwrQM+0CBn+FUnEzK8YRtFbB3WtjkqDawNQcIvNUNe1f+4om/sPcoPojZeJCeTHvInfthd4Wm803HaTh4ch90YTBOshpM=
  - secure: MZJIxqbrBKXpG52s8UrsqaILuml/e0QiWhQYYtpjOYj/xWoC+zMZQephbc5a2SknziHuHlEMQJ6X+L2MEndl5Hl9XYunfl5ehXXvmiltMF5EsnDLE6JEFn9gKtYo6zJOJRUB1Y4tS4sgRCjavwYznx52h/+ipenTaZillSkvZaHQTenA4ZDkuWz/thJ4ZA/iDk8gRXjFvmB1hwVkHO0B6KyP0HYBTXhhYPrKRqKUGiNYhsawRgjkCqrHmMi0DarxE6qKBEh4nMCObqK5yO2aOjZjx0JXOTOqsH3MNS4MiqMvOkAF1ZUkkn80WVAyVXtbqq85xJqpxnads54AgZ62dA/B/+LPGyetTZ5xTMWB4Heiy5UNW9G/jzswUCsL5aS6iVCjCIMbB+LIMm9EqaaViobrr0uDmrEiY/D1VjArCnUGO0gt+Rm+HS6mx4wzSB3pMJz9JdAPvEtypYxeZv5QsCtRxnwY1ErTUe0btza4Wans3wHDZ9kQU6Vne6WTB4NnUUKdycvJFFCpYr9y7RGOzhdtfEqaUpoc34sDS2oZOuOAMKTFgP9eTRyxf+ZeOrOt4XDOT/LKNrEqtYs4GXylwcFwpbh2iQmnJdSNO6OW4BJinVov96R1wwCxe0TngDel8MlarvlG02y5QChHRWzPxZ6ve2AOdv5kJTWFnytgs6Q=
  - secure: OyWH5m5R+ph2y7CrxnXS/pt9q/glPURox30w1o9C9SJ3YMnUQ0IJShYm2Iwwq0hz/yr9u2KAvFwYzUXEOAfXG+LeM/J/i6nQ0g8hQwdxTxkFgOCXqqFdQUvcXmmWr3cCWRUYRrTQXITID4GcreBDRfYIS4VOoEHRxHHeOyzsk4XB8MsKuyQd1COksRNe+3rGMD175zGUhmLk+9noE1368oL7oRuCSkgqB6K4XeaCXuS34aULuEGiNv8oWZ63FzmkWYre6y698ABA4cAe3v+Mp1Z3VmAlsRbHBDj8yxkSZjzk5EFWUWrNp1s+QiAbEwmdnFTQi/f5x60g+0Ko3qI7+GKeYqUdC7BcyUNRQZpWhD0CnEb2TewWa9/hO+Y1Prj7V+ajRYlRDGUyN4IQ+18du66sHBGkGxzLq6SruGB2lTXwdL+uXRj227xW4BaufTE+iF02M/7cGK9/bDohv+5rGCA4WYc/jOYmHLYge3QCtVmJWi473HNpidDHmCyOGZZpgGRL5s1EJqtJhLcGdLhlhN2qNeeQZYYQg7ZNSIYM25ZpnA4OXEVZs4hR+RNU9P5Jix7XUip7nb0OsCNpDhvJQUzMmy+twRPDmIB/tW36lpxzEvjmcKqsl7jYxs73V2DhEN8x03ScHdj8saHbYHUGQL0TjJunlYbYugqTNxvBR5o=
