language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk12
cache:
  directories:
    - ".autoconf"
    - "$HOME/.m2"
    - "$HOME/.cache"
    - "$HOME/.gradle"
script: ./gradlew build
jobs:
  include:
    - stage: Deploy to bintray
      jdk: openjdk8
      script: skip
      if: tag IS present
      deploy:
        provider: script
        script: ./gradlew publishPlugins
        on:
          tag: true
          all_branches: true
env:
  global:
    - secure: Vha2bAijHipu+C6pXCVy5aHGx3GXmidZS4WcIxO6CR1d3vm3ZMvfL6kEn4ddfRDUhBPlzvATFa1UvPqsjD/WKVGvVDblE3hKy40UmfEjhKepl5Pve57Az3GcaPVQC2LPrNibW6os29XTDybf6PnMHm0B6cPK34tWrbqigfxriNaibdWpCrd41ahzE9+cWidGaYSKkTRquYGWL0/aYrEAIggh9R/vhL2KbVm+/VBMOnNsZq+Wfqhq/UHhCg/4FLEBWZZjgABubIhSLyzr4CdgOazLDI2Wd3uMWJcO5ufim8h7OMR/180G2woG1VrVFdJNJQBqi4CON02S0oxkg8QN7j0D3IVje6R+6TSkJxyjVu3TwePRTwDhqwp7tZcS2XE25B09KTeU+E03k2KcQamLlyg8riqmV9F+31Y7qerD8DnMT/N6NywREuRIGYadQniXEV+MzlbAz3JzEGMT/b02rkaZ1GOqnllTmIORkTrVg/V7GE76biakMLICB7m7CeEOhsxhVs3uNHHCXFffONX4hC3N5UnpSyrZb1mptKGNfzACHc45u3NMnqE/elbTEiXJhab/kQPXBZjsfXa070CaqbZ20R10aTilrl4OrHHucMJCRlrvITGJo1X9OZxsQfVuCDcJe8lrO0T9+Af5y0BX+roRIyrEmyker4oetlx92gI=
    - secure: RZVjDdKkGS7JHDiKM5HfM32bHrhYfwIxJyF6Etk1uiqWVMsMoLE8N0AK2b13QDD/l7BpD6dVE9KoXpwHV0v581GfSAL2NLrzIDd8HfxbloGMNAzeAnuQ6MndxO6poMgiHFzj39Ij/VodAHdWcvMeOvIysahuCkgGTcPF76KUGusGHa5TIWnUVXM60NKvfnp7jw55fdThCHuMq4MgCYxuL5Ka1v/spTUFbb2LY2St9FGytyv7VlHVDVGUdFgHbQ6Quiw/3a5kcsei6Yo6guZ4HdP5TljZUwz0Kp7a+YNv2mcGGyltEfdbwq7H48F2Q8OYEG1rYiynFnyDw+KPe9jEcTaFFlk9EA46YM5OheU6ZLF1NZVqRd4E1gGcRoDkgusDbxCdpAqYeryfom9f6m/uoomG9Hqx5mD7JN3b14FnrhQT7q8jnHAwRD86nwzpcFFQzJ6iDajM8F9bJ0Unp/6CwtR8fx7LlcQroWjM5CSDFScFt8Ghk2JA72jXL4Nt9+SqHR4jAXSSuR7vKNtQGhM1Wt07GKVJ4ttRRXJgTqi/Zht81mE7WYDPW4RNkLDhbsLrFsJctFlp/kPymetZYXojti0w6Z2B3qm8ha1293XeXtqIUFhzObIeGS3PjLmTtpAvrvWEM+IbHNepTRsM4RKAs+JBxYAgs3h0h7BWa5HuIbQ=
    - secure: b6pCorGmwMo3RQMPQHxwCzxC1LYKPRgbJly2bvkzwQb+se53ks9QtEJdbjUxsGh5hh9VN2KqoE7DavRpsJPvI6oD0syq6dkWvar25BhWXg41IR5iWbIRH10ZkGnGSPMN5ZNh7X7Xqzt1v/RN4VOoNdRqfoylkCaFD3oGv62vr2yYj0PRkYTdE+XFk+nPpEFxnkgvEEDaR/6XMuOakwqyF96ZOm5MewIjEgOWTzcOEYIv0G+S12OAU7FDROKMUPgv1YD3PWxHM0XlaSu2UZYBblBvdhrUvDfN+G2BIQcgqtaTtsYpI7q4mWXyLejvYDA11SyA7Dq72ftEdXFGkEK6ItygpqElM8FZ3gFwDDyJdQb3eowssFxOF/7aLUQihAFc99D2+2A0Xr7HmH2SuE4VW8XmxwTxqTMKv0x+qot7wmD1Jo1KdfAKI7snQEgnQEL0JBqnsLk1b2o6mbr9k8bOThpLhcyBoCr4GZI+GNZJLAYkWFolSYCqHDh5Owb2CcVjBwqijRCiA1QfRLdqqSBAKIOSZ+T9et2FLv7yog1AteDYaJdpyhxGtng7TGI4HcLVPsD/R5/XF7B57AC2vWy42d7fZU6ZvvtOBpKnUDCNuh21co3rB0M3XLrKR2jdXYkbJdWeUpYWRy62ut4/efd7bykmKh/a6825qtgYMxBIL8Y=
